### ISSUE TITLE
How to start server?

### ISSUE THREAD

**Issue by giosh04** [Frave07/Backend-Delivery-App-Flutter#1]
Hi! Tried many different variants to start. Get

(node:26434) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/admin/Downloads/Backend-Delivery-App-Flutter-main/src/index.js:1
import http from './App';
^^^^^^

SyntaxError: Cannot use import statement outside a module

--- or ----

admin@Admins-MacBook-Air Backend-Delivery-App-Flutter-main % ./node_modules/.bin/babel-node src/index.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/admin/Downloads/Backend-Delivery-App-Flutter-main/src/App' imported from /Users/admin/Downloads/Backend-Delivery-App-Flutter-main/src/index.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Could you please help me?

**Comment by akash-ajith** [comment]
How did you fix this?

**Comment by Frave07** [comment]
![image](https://user-images.githubusercontent.com/76232843/146577282-efaa51d5-6954-4949-a3cf-b1b85f8d323e.png)
Yes., only Git did not upload the Babel file for the EMS6 configuration
